# Generated by Django 5.0.6 on 2024-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('egender', models.CharField(max_length=50)),
                ('eage', models.IntegerField()),
                ('esalary', models.IntegerField()),
                ('eyoe', models.CharField(max_length=200)),
                ('edep', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
    ]
