# Generated by Django 5.0.6 on 2024-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_employee_doj_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
